# Generated by Django 2.1.2 on 2019-01-21 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('mobile', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField(blank=True)),
                ('nationality', models.CharField(choices=[('KOR', 'South Korea'), ('GER', 'Germany')], max_length=20)),
                ('en_level', models.CharField(choices=[('ADV', 'ADVANCED'), ('UI', 'Upper Intermediate'), ('I', 'Intermediate'), ('PI', 'Pre Intermediate')], max_length=40, verbose_name='English Level')),
                ('attached_files', models.FileField(blank=True, upload_to='uploads/')),
                ('submitted', models.DateField(auto_now_add=True)),
                ('username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='register',
            name='username',
        ),
        migrations.DeleteModel(
            name='Register',
        ),
    ]
