# Generated by Django 2.1.2 on 2019-01-23 23:03

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20190121_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='nationality',
        ),
        migrations.AddField(
            model_name='student',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='student',
            name='en_level',
            field=models.CharField(choices=[('ADV', 'Advanced'), ('UI', 'Upper Intermediate'), ('I', 'Intermediate'), ('PI', 'Pre Intermediate')], max_length=40, verbose_name='English Level'),
        ),
    ]
